services:
  postgres:
    image: postgres:14
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - airflow-scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=aoo11y25N9n22Unlg3mbrDvVnI-opvifopkKvbw5VSA=
      - AIRFLOW__WEBSERVER__SECRET_KEY=178af3aeb022810a6050ca44aad9fbdf
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres scikit-learn
    volumes:
      - ./:/opt/airflow
    ports:
      - "8080:8080"
    command: webserver
    user: "${AIRFLOW_UID:-50000}:0"

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=aoo11y25N9n22Unlg3mbrDvVnI-opvifopkKvbw5VSA=
      - AIRFLOW__WEBSERVER__SECRET_KEY=178af3aeb022810a6050ca44aad9fbdf
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres scikit-learn
    volumes:
      - ./:/opt/airflow
    command: scheduler
    user: "${AIRFLOW_UID:-50000}:0"

volumes:
  airflow_postgres_data:
